include: package:very_good_analysis/analysis_options.6.0.0.yaml

linter:
  rules:
    public_member_api_docs: true
    lines_longer_than_80_chars: false

analyzer:
  exclude:
    - coverage/**
    - doc/**
  plugins:
    - custom_lint
